// <auto-generated />
using System;
using DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NEU.Misafirhane.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260928115254_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NEU.Core.Entities.Concrete.DataLog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("kullaniciid")
                        .HasColumnType("bigint");

                    b.Property<string>("tabloislem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tabloismi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.Property<long>("tckimlikno")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("DataLog");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Misafir", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RezervasyonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RezervasyonId");

                    b.ToTable("Misafirler");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Oda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("MaksEkYatak")
                        .HasColumnType("int");

                    b.Property<int>("NormalKapasite")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("OdaTipiId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OdaNo")
                        .IsUnique();

                    b.HasIndex("OdaTipiId");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.OdaKapatma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BitisTarihi")
                        .HasColumnType("date");

                    b.Property<long>("OdaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sebep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.ToTable("OdaKapatmalari");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.OdaTipi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OdaTipleri");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Rezervasyon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("CikisTarihi")
                        .HasColumnType("date");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("EkYatakSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("GirisTarihi")
                        .HasColumnType("date");

                    b.Property<int>("KiralamaTipi")
                        .HasColumnType("int");

                    b.Property<long>("OdaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RezervasyonKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("YatakId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.HasIndex("RezervasyonKodu")
                        .IsUnique();

                    b.HasIndex("YatakId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Yatak", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OdaId")
                        .HasColumnType("bigint");

                    b.Property<int>("YatakNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdaId", "YatakNo")
                        .IsUnique();

                    b.ToTable("Yataklar");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Misafir", b =>
                {
                    b.HasOne("NEU.Misafirhane.Entities.Concrete.Rezervasyon", "Rezervasyon")
                        .WithMany("Misafirler")
                        .HasForeignKey("RezervasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Oda", b =>
                {
                    b.HasOne("NEU.Misafirhane.Entities.Concrete.OdaTipi", "OdaTipi")
                        .WithMany("Odalar")
                        .HasForeignKey("OdaTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OdaTipi");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.OdaKapatma", b =>
                {
                    b.HasOne("NEU.Misafirhane.Entities.Concrete.Oda", "Oda")
                        .WithMany("Kapatmalar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oda");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Rezervasyon", b =>
                {
                    b.HasOne("NEU.Misafirhane.Entities.Concrete.Oda", "Oda")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NEU.Misafirhane.Entities.Concrete.Yatak", "Yatak")
                        .WithMany()
                        .HasForeignKey("YatakId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Oda");

                    b.Navigation("Yatak");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Yatak", b =>
                {
                    b.HasOne("NEU.Misafirhane.Entities.Concrete.Oda", "Oda")
                        .WithMany("Yataklar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oda");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Oda", b =>
                {
                    b.Navigation("Kapatmalar");

                    b.Navigation("Rezervasyonlar");

                    b.Navigation("Yataklar");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.OdaTipi", b =>
                {
                    b.Navigation("Odalar");
                });

            modelBuilder.Entity("NEU.Misafirhane.Entities.Concrete.Rezervasyon", b =>
                {
                    b.Navigation("Misafirler");
                });
#pragma warning restore 612, 618
        }
    }
}
